# */
FROM centos:centos6.9
MAINTAINER wujian@wujian360.cn "Please don't change yourself"

RUN yum install -y http://www.percona.com/downloads/percona-release/redhat/0.1-4/percona-release-0.1-4.noarch.rpm && yum install -y gcc-c++ make gcc httpd php mysql php-mysql php-devel php-pear libssh2 libssh2-devel unzip cmake libaio-devel libffi-devel glib2 glib2-devel Percona-Server-shared-56  bison libaio-devel ncurses-devel && yum clean all && rm -rf /var/lib/mysql

COPY SQLAdvisor /SQLAdvisor

RUN echo '' | pecl install -f ssh2 && ln -s /usr/lib64/libperconaserverclient_r.so.18 /usr/lib64/libperconaserverclient_r.so && cd /SQLAdvisor && cmake -DBUILD_CONFIG=mysql_release -DCMAKE_BUILD_TYPE=debug -DCMAKE_INSTALL_PREFIX=/usr/local/sqlparser ./ && make && make install && cd  /SQLAdvisor/sqladvisor && cmake -DCMAKE_BUILD_TYPE=debug ./  && make   && cp sqladvisor /usr/bin/sqladvisor

CMD ["/SQLAdvisor/run.sh"]