# */
FROM centos:centos6.9
MAINTAINER ppabc@qq.com "ppabc"

COPY SQLAdvisor /SQLAdvisor

RUN chmod +x /SQLAdvisor/install_sqladvisor.sh  && chmod +x /SQLAdvisor/run.sh && bash /SQLAdvisor/install_sqladvisor.sh

CMD ["/SQLAdvisor/run.sh"]